In [1]:
import torch

In [2]:
a = torch.arange(6).reshape(2, 3)
print(a.shape)
a

torch.Size([2, 3])


tensor([[0, 1, 2],
        [3, 4, 5]])

In [3]:
b = torch.arange(3)
print(b.shape)
b

torch.Size([3])


tensor([0, 1, 2])

In [4]:
c = torch.arange(15).reshape(3, 5)
print(c.shape)
c

torch.Size([3, 5])


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [5]:
d = torch.arange(3, 6)
print(d.shape)
d

torch.Size([3])


tensor([3, 4, 5])

In [6]:
e = torch.arange(6, 12).reshape(2, 3)
print(e.shape)
e

torch.Size([2, 3])


tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [22]:
f = torch.arange(3, 7)
print(f.shape)
f

torch.Size([4])


tensor([3, 4, 5, 6])

In [31]:
g = torch.randn(3, 2, 5)
print(g.shape)
g

torch.Size([3, 2, 5])


tensor([[[ 0.3768, -0.6982, -1.6768, -1.3086,  0.6610],
         [ 0.9244,  1.5438,  0.2032, -0.1598,  0.1851]],

        [[ 0.2921,  0.6879, -0.0167, -0.1346,  0.8065],
         [-1.1628, -1.7981, -0.1475, -0.4963,  0.8500]],

        [[ 0.4239, -1.8685, -0.8506,  0.3479, -0.7514],
         [ 1.1026, -0.2001,  0.6594, -0.4358,  0.1588]]])

In [32]:
h = torch.randn(3, 5, 3)
print(h.shape)
h

torch.Size([3, 5, 3])


tensor([[[ 0.0368,  0.2877,  0.2395],
         [-1.2786, -2.0343, -1.4348],
         [-0.8768,  1.7687,  0.3995],
         [ 0.5961, -0.6631,  0.2530],
         [ 1.7248,  2.2300, -0.5085]],

        [[ 1.0851, -0.4784,  0.2140],
         [ 0.2894,  0.7142, -1.7932],
         [ 1.3738, -0.6796, -0.0524],
         [ 0.6204,  0.6111, -1.9624],
         [-0.1463,  0.4011, -0.4859]],

        [[ 0.5194, -0.3192,  0.9166],
         [-1.4423, -0.0698,  0.2377],
         [ 1.2781, -0.1254, -0.3137],
         [ 1.9637, -1.6561, -0.1307],
         [ 1.5982, -1.1188,  0.6976]]])

In [7]:
# Transpose
print(a.T)
torch.einsum("ij->ji", [a])

tensor([[0, 3],
        [1, 4],
        [2, 5]])


tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [8]:
# Sum
print(a.sum())
torch.einsum("ij->", [a])

tensor(15)


tensor(15)

In [9]:
# Column Sum
print(a.sum(dim=0))
torch.einsum("ij->j", [a])

tensor([3, 5, 7])


tensor([3, 5, 7])

In [10]:
# Row Sum
print(a.sum(dim=1))
torch.einsum("ij->i", [a])

tensor([ 3, 12])


tensor([ 3, 12])

In [11]:
# Matrix @ Vector
print(a @ b)
torch.einsum("ij,j->i", [a, b])

tensor([ 5, 14])


tensor([ 5, 14])

In [12]:
# Matrix @ Matrix
print(a @ c)
torch.einsum("ij,jk->ik", [a, c])

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])


tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

In [13]:
# Vector Dot Product
print(b @ d)
torch.einsum("i,i->", [b, d])

tensor(14)


tensor(14)

In [30]:
# Matrix Dot Product
print(a * e)
print((a * e).sum())
torch.einsum("ij,ij->", [a, e])

tensor([[ 0,  7, 16],
        [27, 40, 55]])
tensor(145)


tensor(145)

In [21]:
# Hadamard Product
print(a * e)
torch.einsum("ij,ij->ij", [a, e])

tensor([[ 0,  7, 16],
        [27, 40, 55]])


tensor([[ 0,  7, 16],
        [27, 40, 55]])

In [29]:
# Outer Product
print(b.unsqueeze(1))
print(f.unsqueeze(0))
print(b.unsqueeze(1) * f.unsqueeze(0))
torch.einsum("i,j->ij", [b, f])

tensor([[0],
        [1],
        [2]])
tensor([[3, 4, 5, 6]])
tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])


tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])

In [35]:
# Batch Matrix Multiplication
print(g @ h)
torch.einsum("ijk,ikl->ijl", [g, h])

tensor([[[ 2.7368,  0.9047, -0.2452],
         [-1.8942, -1.9965, -2.0471]],

        [[ 0.2916,  0.6042, -1.2978],
         [-2.4171, -0.5900,  3.5441]],

        [[ 1.3100,  0.3663, -0.3585],
         [ 1.1020,  0.1234,  0.9240]]])


tensor([[[ 2.7368,  0.9047, -0.2452],
         [-1.8942, -1.9965, -2.0471]],

        [[ 0.2916,  0.6042, -1.2978],
         [-2.4171, -0.5900,  3.5441]],

        [[ 1.3100,  0.3663, -0.3585],
         [ 1.1020,  0.1234,  0.9240]]])