In [1]:
import torch

In [2]:
a = torch.arange(6).reshape(2, 3)
print(a.shape)
a

torch.Size([2, 3])


tensor([[0, 1, 2],
        [3, 4, 5]])

In [3]:
b = torch.arange(3)
print(b.shape)
b

torch.Size([3])


tensor([0, 1, 2])

In [4]:
c = torch.arange(15).reshape(3, 5)
print(c.shape)
c

torch.Size([3, 5])


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [5]:
d = torch.arange(3, 6)
print(d.shape)
d

torch.Size([3])


tensor([3, 4, 5])

In [6]:
e = torch.arange(6, 12).reshape(2, 3)
print(e.shape)
e

torch.Size([2, 3])


tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

In [22]:
f = torch.arange(3, 7)
print(f.shape)
f

torch.Size([4])


tensor([3, 4, 5, 6])

In [7]:
# Transpose
print(a.T)
torch.einsum("ij->ji", [a])

tensor([[0, 3],
        [1, 4],
        [2, 5]])


tensor([[0, 3],
        [1, 4],
        [2, 5]])

In [8]:
# Sum
print(a.sum())
torch.einsum("ij->", [a])

tensor(15)


tensor(15)

In [9]:
# Column Sum
print(a.sum(dim=0))
torch.einsum("ij->j", [a])

tensor([3, 5, 7])


tensor([3, 5, 7])

In [10]:
# Row Sum
print(a.sum(dim=1))
torch.einsum("ij->i", [a])

tensor([ 3, 12])


tensor([ 3, 12])

In [11]:
# Matrix @ Vector
print(a @ b)
torch.einsum("ij,j->i", [a, b])

tensor([ 5, 14])


tensor([ 5, 14])

In [12]:
# Matrix @ Matrix
print(a @ c)
torch.einsum("ij,jk->ik", [a, c])

tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])


tensor([[ 25,  28,  31,  34,  37],
        [ 70,  82,  94, 106, 118]])

In [13]:
# Vector Dot Product
print(b @ d)
torch.einsum("i,i->", [b, d])

tensor(14)


tensor(14)

In [30]:
# Matrix Dot Product
print(a * e)
print((a * e).sum())
torch.einsum("ij,ij->", [a, e])

tensor([[ 0,  7, 16],
        [27, 40, 55]])
tensor(145)


tensor(145)

In [21]:
# Hadamard Product
print(a * e)
torch.einsum("ij,ij->ij", [a, e])

tensor([[ 0,  7, 16],
        [27, 40, 55]])


tensor([[ 0,  7, 16],
        [27, 40, 55]])

In [29]:
# Outer Product
print(b.unsqueeze(1))
print(f.unsqueeze(0))
print(b.unsqueeze(1) * f.unsqueeze(0))
torch.einsum("i,j->ij", [b, f])

tensor([[0],
        [1],
        [2]])
tensor([[3, 4, 5, 6]])
tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])


tensor([[ 0,  0,  0,  0],
        [ 3,  4,  5,  6],
        [ 6,  8, 10, 12]])